[workspace]
authors = ["owen-m1ller <omiller@ucsd.edu>"]
channels = ["conda-forge"]
name = "plantLOT"
platforms = ["linux-64", "osx-arm64", "win64"]
version = "0.1.0"

[tasks]

[dependencies]
open3d = ">=0.19.0,<0.20"
python = ">=3.14.0,<3.15"
pot = ">=0.9.6.post1,<0.10"
matplotlib = ">=3.10.7,<4"
ipykernel = ">=7.1.0,<8"
jupyterlab = ">=4.4.10,<5"
numpy = ">=2.3.4,<3"
